name: Checking changeset
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Rush Install
        # Pinning to specific commit that has been audited. Only update 3rd party
        # actions' commit hashes if you've audited them
        uses: advancedcsg-open/actions-rush@981bd2de50c1c39dbb8a537e646ee0c410da8638

      - name: Rush link
        run: rush link

      - name: Rush build
        run: rush rebuild --verbose

      - name: Check for changes
        run: rush change --verify
